apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: articles-api-http-route
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tagenal`) && PathPrefix(`/articles`)
      services:
        - name: articles-api-service
          port: 8080
      middlewares:
        - name: articles-api-http-route-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: articles-api-http-route-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /articles
      - /articles/
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: articles-api-grpc-route
spec:
  entryPoints:
    - grpc
  routes:
    - kind: Rule
      match: HostSNI(`*`)
      services:
        - name: articles-api-service
          port: 9090
