language: go

go:
- 1.15.5

jobs:
  include:
    - stage: test build
      install:
        - make -C api/articles deps
        - make -C api/users deps
        - make -C frontend deps
        - go get -d -v google.golang.org/grpc/...
      script:
        - make -C api/articles build
        - make -C api/users build
        - make -C api/users test
        - make -C frontend build
      