DROP TABLE IF EXISTS users_lookup;
DROP TABLE IF EXISTS user_read;
DROP TABLE IF EXISTS user;

CREATE TABLE users_lookup (
  id INT NOT NULL,
  keyspace_id VARBINARY(128),

  PRIMARY KEY(id)
);

CREATE TABLE user (
  id INT NOT NULL,
  timestamp CHAR(14) DEFAULT NULL,
  uid CHAR(5) DEFAULT NULL,
  name CHAR(9) DEFAULT NULL,
  gender CHAR(7) DEFAULT NULL,
  email CHAR(10) DEFAULT NULL,
  phone CHAR(10) DEFAULT NULL,
  dept CHAR(9) DEFAULT NULL,
  grade CHAR(7) DEFAULT NULL,
  language CHAR(3) DEFAULT NULL,
  region VARBINARY(256),
  role CHAR(6) DEFAULT NULL,
  preferTags CHAR(7) DEFAULT NULL,
  obtainedCredits CHAR(3) DEFAULT NULL,
  
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_read (
  id INT NOT NULL,
  timestamp CHAR(14) DEFAULT NULL,
  uid INT NOT NULL,
  aid CHAR(7) DEFAULT NULL,
  readOrNot CHAR(2) DEFAULT NULL,
  readTimeLength CHAR(3) DEFAULT NULL,
  readSequence CHAR(2) DEFAULT NULL,
  agreeOrNot CHAR(2) DEFAULT NULL,
  commentOrNot CHAR(2) DEFAULT NULL,
  shareOrNot CHAR(2) DEFAULT NULL,
  commentDetail CHAR(100) DEFAULT NULL,

  PRIMARY KEY(id),

  FOREIGN KEY(uid) REFERENCES user(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
