apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  annotations:
    "sidecar.jaegertracing.io/inject": "jaeger-prod"
  labels:
    api: users
    app: users-api
    tier: backend
spec:
  selector:
    matchLabels:
      app: users-api
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: users-api
        tier: backend
    spec:
      containers:
        - name: users-api-server
          image: frouioui/tagenal-users-service:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: grpc
              containerPort: 9090
            - name: http
              containerPort: 10000
          env:
            - name: JAEGER_SERVICE_NAME
              value: "api-users"
            - name: REDIS_MASTER_HOSTNAME
              value: "redis-cluster.redis"
            - name: REDIS_MASTER_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
    api: users
    app: users-api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: users-api
    tier: backend
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc
    - port: 10000
      targetPort: 10000
      name: http
