apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  annotations:
    "sidecar.jaegertracing.io/inject": "jaeger-prod"
  labels:
    api: users
    app: users-api
    tier: backend
spec:
  selector:
    matchLabels:
      app: users-api
      tier: backend
  replicas: 2
  strategy:
    rollingUpdate:
      # Only a few replicas. Not a lot of resources will be used during
      # rolling updates with a 50% surge.
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  # Development environment, no need for a big history.
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 240
  template:
    metadata:
      labels:
        app: users-api
        tier: backend
      annotations:
        kubernetes.io/change-cause: "Addition of liveness and readiness probes"
    spec:
      containers:
        - name: users-api-server
          image: frouioui/tagenal-users-service:latest
          livenessProbe:
              httpGet:
                path: /health
                port: 10000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 1
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /ready
                port: 10000
              initialDelaySeconds: 1
              periodSeconds: 1
              timeoutSeconds: 1
              failureThreshold: 3
              successThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: grpc
              containerPort: 9090
            - name: http
              containerPort: 10000
          env:
            - name: JAEGER_SERVICE_NAME
              value: "api-users"
            - name: REDIS_MASTER_HOSTNAME
              value: "redis-cluster.redis"
            - name: REDIS_MASTER_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
    api: users
    app: users-api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: users-api
    tier: backend
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc
    - port: 10000
      targetPort: 10000
      name: http
