apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagenal-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "jaeger-prod"
  labels:
    app: tagenal-frontend
spec:
  selector:
    matchLabels:
      app: tagenal-frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 240
  template:
    metadata:
      labels:
        app: tagenal-frontend
      annotations:
        kubernetes.io/change-cause: "Addition of liveness and readiness probes"
    spec:
      containers:
        - name: tagenal-frontend
          image: frouioui/tagenal-frontend-service:latest
          imagePullPolicy: Always
          livenessProbe:
              httpGet:
                path: /health
                port: 8888
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /ready
                port: 8888
              initialDelaySeconds: 2
              periodSeconds: 2
              timeoutSeconds: 2
              failureThreshold: 3
              successThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: web
              containerPort: 8888
          env:
            - name: JAEGER_SERVICE_NAME
              value: "frontend"
            - name: DATA_ASSETS_PATH
              value: "/assets/data"
            - name: STATIC_PATH
              value: "/static/data"
          volumeMounts:
            - name: assets
              mountPath: /assets/data
      volumes:
      - name: assets
        hostPath:
          path: /mount_data/data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: tagenal-frontend-service
spec:
  type: ClusterIP
  selector:
    app: tagenal-frontend
  ports:
    - port: 8888
      targetPort: 8888
      name: web
