apiVersion: v1
kind: Namespace
metadata:
  name:  redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: redis
  labels:
    app: redis
data:
  cluster.conf: |
    maxmemory 5mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      namespace: redis
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        command:
          - redis-server
          - "/redis-master/cluster.conf"
        env:
        - name: MASTER
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /redis-master-data
            name: data
          - mountPath: /redis-master/cluster.conf
            name: config
            subPath: cluster.conf
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-configmap
---        
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      namespace: redis
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: redis
        command:
          - redis-server
          - --slaveof redis-master 6379
        env:
        - name: MASTER
          value: "false"
        - name: MASTER_HOST
          value: "redis-master"
        - name: MASTER_PORT
          value: "6379"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
