apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: vitess
  namespace: vitess
spec:
  images:
    vtctld: vitess/lite:v8.0.0
    vtgate: vitess/lite:v8.0.0
    vttablet: vitess/lite:v8.0.0
    vtbackup: vitess/lite:v8.0.0
    mysqld:
      mysql56Compatible: vitess/lite:v8.0.0
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
    - name: zone1 # VTGATE
      gateway:
        authentication:
          static:
            secret:
              name: vitess-cluster-secret
              key: users.json
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
        extraVolumeMounts:
          - name: vitess-region-config-volume
            mountPath: /tmp/countries.json
            subPath: countries.json
          - name: vitess-region-config-volume
            mountPath: /tmp/categories.json
            subPath: categories.json
        extraVolumes:
          - name: vitess-region-config-volume
            configMap:
              name: vitess-cluster-config-sharding
  vitessDashboard: # VTCTLD
    cells:
      - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    extraVolumeMounts:
      - name: vitess-region-config-volume
        mountPath: /tmp/countries.json
        subPath: countries.json
      - name: vitess-region-config-volume
        mountPath: /tmp/categories.json
        subPath: categories.json
    extraVolumes:
      - name: vitess-region-config-volume
        configMap:
          name: vitess-cluster-config-sharding
  keyspaces:
    - name: articles
      turndownPolicy: Immediate
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-cluster-secret
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  extraVolumeMounts:
                    - name: vitess-region-config-volume
                      mountPath: /tmp/categories.json
                      subPath: categories.json
                  extraVolumes:
                    - name: vitess-region-config-volume
                      configMap:
                        name: vitess-cluster-config-sharding
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
        - equal:
            parts: 2
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-cluster-secret
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
                  extraVolumeMounts:
                    - name: vitess-region-config-volume
                      mountPath: /tmp/categories.json
                      subPath: categories.json
                  extraVolumes:
                    - name: vitess-region-config-volume
                      configMap:
                        name: vitess-cluster-config-sharding

    - name: users
      turndownPolicy: Immediate
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-cluster-secret
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  extraVolumeMounts:
                    - name: vitess-region-config-volume
                      mountPath: /tmp/countries.json
                      subPath: countries.json
                  extraVolumes:
                    - name: vitess-region-config-volume
                      configMap:
                        name: vitess-cluster-config-sharding
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
        - equal:
            parts: 2
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-cluster-secret
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
                  extraVolumeMounts:
                    - name: vitess-region-config-volume
                      mountPath: /tmp/countries.json
                      subPath: countries.json
                  extraVolumes:
                    - name: vitess-region-config-volume
                      configMap:
                        name: vitess-cluster-config-sharding

    - name: config
      turndownPolicy: Immediate
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-cluster-secret
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
  updateStrategy:
    type: Immediate
