apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vtctld-web
  namespace: vitess
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tagenal`) && PathPrefix(`/vtctld`)
      services:
        - namespace: vitess
          name: vitess-vtctld-047eb1a6
          port: 15000
      middlewares:
        - namespace: vitess
          name: vtctld-web-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: vtctld-web-stripprefix
  namespace: vitess
spec:
  stripPrefix:
    prefixes:
      - /vtctld
