kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
  selector:
    app: whoami
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tagenal`) && PathPrefix(`/whoami`)
      services:
        - name: whoami
          port: 80
